// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20220728133520_ChengedSeedForArr")]
    partial class ChengedSeedForArr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArrangementArrangementGroup", b =>
                {
                    b.Property<int>("ArrangementsGroupArrangementGroupID")
                        .HasColumnType("integer");

                    b.Property<int>("ArrangementsArrangementID")
                        .HasColumnType("integer");

                    b.Property<int>("ArrangementsTravelCompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("ArrangementsTravelPlaceID")
                        .HasColumnType("integer");

                    b.HasKey("ArrangementsGroupArrangementGroupID", "ArrangementsArrangementID", "ArrangementsTravelCompanyID", "ArrangementsTravelPlaceID");

                    b.HasIndex("ArrangementsArrangementID", "ArrangementsTravelCompanyID", "ArrangementsTravelPlaceID");

                    b.ToTable("ArrangementArrangementGroup");
                });

            modelBuilder.Entity("Models.Arrangement", b =>
                {
                    b.Property<int>("ArrangementID")
                        .HasColumnType("integer");

                    b.Property<int>("TravelCompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("TravelPlaceID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("OnlyAirplaneTicket")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("SeatsInArrangement")
                        .HasColumnType("integer");

                    b.Property<int>("StartPlaceID")
                        .HasColumnType("integer");

                    b.HasKey("ArrangementID", "TravelCompanyID", "TravelPlaceID");

                    b.HasIndex("TravelCompanyID");

                    b.HasIndex("TravelPlaceID");

                    b.ToTable("Arrangements");

                    b.HasData(
                        new
                        {
                            ArrangementID = 1,
                            TravelCompanyID = 2,
                            TravelPlaceID = 4,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 123.22,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 2,
                            TravelCompanyID = 5,
                            TravelPlaceID = 3,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 117.98999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 3,
                            TravelCompanyID = 1,
                            TravelPlaceID = 5,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 126.12,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 4,
                            TravelCompanyID = 6,
                            TravelPlaceID = 21,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 72.319999999999993,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 5,
                            TravelCompanyID = 3,
                            TravelPlaceID = 4,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 223.22,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 6,
                            TravelCompanyID = 2,
                            TravelPlaceID = 3,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 217.99000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 7,
                            TravelCompanyID = 4,
                            TravelPlaceID = 5,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 226.12,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 8,
                            TravelCompanyID = 3,
                            TravelPlaceID = 21,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 272.31999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 9,
                            TravelCompanyID = 1,
                            TravelPlaceID = 1,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 1212.1199999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 10,
                            TravelCompanyID = 2,
                            TravelPlaceID = 2,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 142.50999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 11,
                            TravelCompanyID = 3,
                            TravelPlaceID = 6,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 436.31999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 12,
                            TravelCompanyID = 4,
                            TravelPlaceID = 7,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 45.719999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 13,
                            TravelCompanyID = 5,
                            TravelPlaceID = 8,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 834.34000000000003,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 14,
                            TravelCompanyID = 6,
                            TravelPlaceID = 9,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 125.34,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 15,
                            TravelCompanyID = 7,
                            TravelPlaceID = 10,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 345.23000000000002,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 16,
                            TravelCompanyID = 6,
                            TravelPlaceID = 11,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 373.33999999999997,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 17,
                            TravelCompanyID = 5,
                            TravelPlaceID = 12,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 612.24000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 18,
                            TravelCompanyID = 4,
                            TravelPlaceID = 13,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 247.99000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 19,
                            TravelCompanyID = 3,
                            TravelPlaceID = 14,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 326.12,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 20,
                            TravelCompanyID = 2,
                            TravelPlaceID = 15,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 261.31999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 21,
                            TravelCompanyID = 1,
                            TravelPlaceID = 16,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 223.22,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 22,
                            TravelCompanyID = 2,
                            TravelPlaceID = 17,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 617.99000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 23,
                            TravelCompanyID = 3,
                            TravelPlaceID = 18,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 526.12,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 24,
                            TravelCompanyID = 4,
                            TravelPlaceID = 19,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 213.31999999999999,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 25,
                            TravelCompanyID = 5,
                            TravelPlaceID = 20,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 523.22000000000003,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 26,
                            TravelCompanyID = 6,
                            TravelPlaceID = 21,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 227.99000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 27,
                            TravelCompanyID = 7,
                            TravelPlaceID = 15,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 426.12,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 28,
                            TravelCompanyID = 1,
                            TravelPlaceID = 14,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 672.32000000000005,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 29,
                            TravelCompanyID = 1,
                            TravelPlaceID = 17,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 213.22,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 30,
                            TravelCompanyID = 3,
                            TravelPlaceID = 17,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 237.99000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 31,
                            TravelCompanyID = 4,
                            TravelPlaceID = 17,
                            DateEnd = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 426.12,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 32,
                            TravelCompanyID = 5,
                            TravelPlaceID = 17,
                            DateStart = new DateTime(2022, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = true,
                            Price = 312.20999999999998,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 33,
                            TravelCompanyID = 6,
                            TravelPlaceID = 17,
                            DateEnd = new DateTime(2022, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 243.22,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        },
                        new
                        {
                            ArrangementID = 34,
                            TravelCompanyID = 7,
                            TravelPlaceID = 17,
                            DateEnd = new DateTime(2022, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2022, 9, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OnlyAirplaneTicket = false,
                            Price = 327.99000000000001,
                            SeatsInArrangement = 10,
                            StartPlaceID = 0
                        });
                });

            modelBuilder.Entity("Models.ArrangementGroup", b =>
                {
                    b.Property<int>("ArrangementGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArrangementGroupID"));

                    b.Property<List<int>>("ArrangementsIDs")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ArrangementGroupID");

                    b.ToTable("ArrangementGroups");
                });

            modelBuilder.Entity("Models.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("NamePermission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionID");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionID = 1,
                            NamePermission = "Delete user"
                        },
                        new
                        {
                            PermissionID = 2,
                            NamePermission = "Insert user"
                        },
                        new
                        {
                            PermissionID = 3,
                            NamePermission = "Access basic data"
                        },
                        new
                        {
                            PermissionID = 4,
                            NamePermission = "Access advences data"
                        });
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleID = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Models.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            PermissionID = 1
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 2
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 3
                        },
                        new
                        {
                            RoleID = 1,
                            PermissionID = 4
                        },
                        new
                        {
                            RoleID = 2,
                            PermissionID = 3
                        });
                });

            modelBuilder.Entity("Models.TravelCompany", b =>
                {
                    b.Property<int>("TravelCompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TravelCompanyID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TravelCompanyID");

                    b.ToTable("TravelCompanies");

                    b.HasData(
                        new
                        {
                            TravelCompanyID = 1,
                            ImageUrl = "https://i.pinimg.com/originals/36/60/eb/3660eb409de95cf3b7845fbd529672d5.jpg",
                            Name = "Expedia Group"
                        },
                        new
                        {
                            TravelCompanyID = 2,
                            ImageUrl = "https://www.breakingtravelnews.com/images/sized/images/uploads/association/American_Express_Global_Business_travel-410x250.png",
                            Name = "American Express Global Business Travel"
                        },
                        new
                        {
                            TravelCompanyID = 3,
                            ImageUrl = "https://www.logolynx.com/images/logolynx/45/45e2d21832a6c5bd9b8535500eb6f988.jpeg",
                            Name = "BCD Travel"
                        },
                        new
                        {
                            TravelCompanyID = 4,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGFY6ACLcnZRRQHxCfeAoarnhQ2WFYNGIjYwj1--ROVHv8KSC3rh0BBn7LJM4mzy8gT_w&usqp=CAU",
                            Name = "CWT"
                        },
                        new
                        {
                            TravelCompanyID = 5,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/c9/Flight_Centre_Canada_Logo.png",
                            Name = "Flight Centre Travel Group"
                        },
                        new
                        {
                            TravelCompanyID = 6,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpPcnJXpBYR9oWJNGY8Y61X4dMaHZbuPZ8ab8GOeTTjCDsXX9afgWFFrhSzqm9707ati8&usqp=CAU",
                            Name = "Travel Leaders Group"
                        },
                        new
                        {
                            TravelCompanyID = 7,
                            ImageUrl = "https://cdn.travelpulse.com/images/bd2ed357-9adc-bb59-4f8f-1e08b5932b51/0b77cb8d-aa17-4bd4-b861-bebe0b369269/500x309.jpg",
                            Name = "American Express"
                        });
                });

            modelBuilder.Entity("Models.TravelPlace", b =>
                {
                    b.Property<int>("TravelPlaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TravelPlaceID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TravelPlaceID");

                    b.ToTable("TravelPlaces");

                    b.HasData(
                        new
                        {
                            TravelPlaceID = 1,
                            Country = "Serbia",
                            Description = "Welcome to Kopaonik - a tourist destination that provides the best vacations. Here you will find everything you need to organize your stay on the mountain. Kopaonik has a lot to offer, so you need a reliable guide through its offer. Find quality accommodation units, choose restaurants with the most varied menu, discover which are the most attractive mountain facilities. Choose the options that best fit the image of your ideal vacation. Prepare to travel in the best way and provide yourself and your companions with the perfect mountain experience.",
                            ImageUrl = "https://www.infokop.net/mambots/content/multithumb/images/b.800.600.0.1.stories.vesti.2019.zima.ski-opening-2018.jpg",
                            Name = "Kopaonik - Skiing"
                        },
                        new
                        {
                            TravelPlaceID = 2,
                            Country = "France",
                            Description = "There are over 150 museums in Paris, including some of the most-visited in the world. As a visitor, the real challenge is choosing the right museums for you, the ones that match your interests, needs, and time. Right now we're going to concentrate on the biggest and the best. Paris is very popular, and so are its museums. You likely will encounter long ticket line-ups at the top museums. If you know us, you'll know we hate standing in lines. So, we appreciate the benefits of the Paris Insiders Pass — a worthwhile tool both to save money and to skip the long lines.",
                            ImageUrl = "https://www.ceeh.es/wp-content/uploads/2021/06/b.jpg",
                            Name = "Paris - Museum"
                        },
                        new
                        {
                            TravelPlaceID = 3,
                            Country = "Iceland",
                            Description = "Iceland's nature is easily the highlight of the entire country. The island features glittering glacier lagoons, bubbling hot springs, and powerful waterfalls – illuminated each season by either the Northern Lights or the Midnight Sun. With its countless natural wonders, it's easy to see why Iceland has become one of the top travel destinations in the world. Below we have listed some of our favorite must-see destinations and must-do experiences that should be on every visitor's bucket list!",
                            ImageUrl = "https://www.telegraph.co.uk/content/dam/Travel/Destinations/Europe/Iceland/Reykjavik/reykjavik-guide-lead-image-48-hours-xlarge.jpg?imwidth=640",
                            Name = "Iceland - Country of ice and fire"
                        },
                        new
                        {
                            TravelPlaceID = 4,
                            Country = "Canada",
                            Description = "The beauty of Canada from east to west is amazing and wonderfully scenic. Although the world is slowly going back to normal, there are however still some flight travels being restricted due to the COVID-19 pandemic. Don’t worry, there is always a good time for some of the best road trips in Canada. If you already live in Canada, you know that the country is worth exploring and full of fantastic nature destinations that attract millions of tourists and adventurers from all around the world. If you're coming from outside the country, then you want to make sure to get an international driver's license for Canada so that you can drive from coast to coast and visit every destination on your way. Now let’s check out some of the top nature travel destinations you must visit in Canada!",
                            ImageUrl = "https://cdn.ceoworld.biz/wp-content/uploads/2022/04/Benefits-of-Holding-a-Canadia-Passport.jpg",
                            Name = "Canada - Nature"
                        },
                        new
                        {
                            TravelPlaceID = 5,
                            Country = "Norway",
                            Description = "Between late September and late March, Northern Norway is dark from early afternoon until late morning, and the northern lights frequently soar across the sky. Our bold claim is that this part of Norway, with its multiple islands, deep fjords and steep mountains, is among the most beautiful and interesting places to see the northern lights.As hundreds of thousands of people live in this huge geographical area, the region of Northern Norway has everything from cities with a lively night scene and great museums to small fishing villages and vast, tranquil spaces without light pollution.This means that in addition to hunting for the northern lights, you can go winter fishing, hiking, skiing, and dog sledding, experience the Sami culture, or join a whale or wildlife safari. Afterwards, you can relax in top-notch hotels and eat incredible local food. Or maybe you’ve joined a northern lights safari and get to eat your meal in a traditional lavvo?",
                            ImageUrl = "https://cdn.kimkim.com/files/a/content_articles/featured_photos/9e76018b4dbc115cd4f8a51f0a49a9948a28cb74/big-2d3b3fc973f25a6a9252308e46b35546.jpg",
                            Name = "Norway - aurora borealis"
                        },
                        new
                        {
                            TravelPlaceID = 6,
                            Country = "India",
                            Description = "India’s natural beauty can rival that of any other country in the world. But while the country’s beaches and mountains are already thoroughly explored, its jungles have come into sharp focus in recent years. With terms such as jungle trekking and forest bathing becoming tourism buzzwords, India’s jungles, national parks and forest reserves are now drawing more visitors than ever. So if jungle trekking is on your mind, here are some of the best places that deserve your attention.",
                            ImageUrl = "https://i.pinimg.com/736x/c2/b8/85/c2b88548dd9f646948c27caa3131ea6e.jpg",
                            Name = "India Jungles"
                        },
                        new
                        {
                            TravelPlaceID = 7,
                            Country = "Australia",
                            Description = "From the 180-million-year-old Daintree Rainforest in the north of Queensland to the cool, misty temperate rainforests of Tasmania, Australia’s rainforests can be found right across the country. Encompassing UNESCO World Heritage areas and hundreds of national parks and reserves, these rainforests are home to an extraordinary variety of plants and animals, and are packed with spectacular waterfalls, idyllic swimming holes, breathtaking hiking trails, and much more. They might be wild, but exploring them is easy.",
                            ImageUrl = "https://travel.mqcdn.com/mapquest/travel/wp-content/uploads/2020/06/GettyImages-676934538-e1592461667985-835x480.jpg",
                            Name = "Australia Jungles"
                        },
                        new
                        {
                            TravelPlaceID = 8,
                            Country = "Australia",
                            Description = "Central Australia lies not only in the heart of Australia; it lies in the hearts of Australians. This region holds not only one of the most culturally significant icons of Aboriginal and Australian culture, Uluru/Ayers Rock; it holds onto the true Outback spirit that made this country great. Whether youre a born-and-bred Australian or visitor from abroad, touring The Centre gives you an appreciation of the vast and unspoiled wonders of Australias interior. Nature overwhelms you in The Centre. The skyscrapers are made out of rock, not steel, and one of the best shows in town is the million-star display at night. The large population of unique animals, birds and reptiles proves that this arid climate is more than hospitable. Wallabies, dingoes, emus, tiny geckos and huge eagles are just some of the long-established locals youll see around The Centre, as well as camels, well-adjusted immigrants to the region.",
                            ImageUrl = "https://www.traveller.com.au/content/dam/images/1/0/7/5/k/n/image.related.articleLeadwide.620x349.zsbg7.png/1425452937659.jpg",
                            Name = "Central Ausralia"
                        },
                        new
                        {
                            TravelPlaceID = 9,
                            Country = "South Africa",
                            Description = "The Cape of Good Hope Nature Reserve forms part of the Cape Peninsula Park and is managed by the South African National Parks. The Nature Reserve is recognized globally for its extraordinary land formation, rich and diverse fauna and unique flora. Nowhere else in the world does an area of such spectacular beauty and such rich biodiversity exist almost within a metropolitan area - the thriving and cosmopolitan City of Cape Town.",
                            ImageUrl = "https://media.cntraveler.com/photos/5b742b0cde8e29470d34f562/16:9/w_2560,c_limit/Cape-of-Good-Hope_GettyImages-962634118.jpg",
                            Name = "Cape of good hope"
                        },
                        new
                        {
                            TravelPlaceID = 10,
                            Country = "Morocco",
                            Description = "Want to discover Rabat? There are a thousand and one ways to do so. A coastal city, its shoreline stretches along nearly 60 kilometres of land with a succession of rocky creeks and fine sandy beaches and its hinterland offers an ecological diversity ideal for hiking.Rabat is the administrative capital of Morocco, it is located on the Atlantic coast and on the left or south bank of the mouth of the Bouregreg, opposite the town of Salé. These two cities are for this reason referred to as twin cities.",
                            ImageUrl = "https://eeradicalization.com/wp-content/uploads/2020/03/ccimage-shutterstock_1075717346.jpg",
                            Name = "Rabat-Cultures of ancient times"
                        },
                        new
                        {
                            TravelPlaceID = 11,
                            Country = "Brazil",
                            Description = "Rio de Janeiro is a bustling and modern beachfront city, with something for tourists to see and do on and off the sand 12 months out of the year. Weather wise, December through March (Brazil's summer months) and September through November (spring in Brazil) means temperatures in the 70s to 90s and little rain. With Carnival comes crowds in February or March, but that's half the fun. It's no surprise New Year's Eve is another epically popular time to party in Rio.",
                            ImageUrl = "http://thehumanist.com/wp-content/uploads/2015/03/statue.jpg",
                            Name = "Rio De Janeiro statue"
                        },
                        new
                        {
                            TravelPlaceID = 12,
                            Country = "Egypt",
                            Description = "Giza's Great Pyramid (also called the Pyramid of Cheops) is not only this ancient site's most famous monument but one of the most well-known monuments in the world.It was built by the Pharaoh Khufu (commonly called by its Greek transliteration of Cheops) and was known to the ancient Egyptians as Ekhet Khufu (Horizon of Khufu).According to Herodotus,10 000 men worked on its construction for three months every year.This mammoth structure's cubic content is staggering. Excluding the rock foundation and the interior chambers, the Great Pyramid is 2.3 million cubic meters. The base measurement is 227.5 meters, and the vertical height is 137.2 meters.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLN31eVZKvcBDST2b-ehzDBBqI2X38aN_bRQTIRnY_dOVw7_ycyKLxTCBLywFRnJ4VzTs&usqp=CAU",
                            Name = "Cairo piramides"
                        },
                        new
                        {
                            TravelPlaceID = 13,
                            Country = "China",
                            Description = "No one should skip Beijing even if only visiting one city/region in China. Beijing is a window into the authentic core of China, especially recommended for China first timers. As one of the world's great ancient capitals, and the capital of the world's upcoming superpower, Beijing is the most important and interesting city in China to travel, both for tourism and understanding China.",
                            ImageUrl = "http://chinaflowers.net/blog/wp-content/uploads/2011/11/beijing_1.jpg",
                            Name = "Beijing culture"
                        },
                        new
                        {
                            TravelPlaceID = 14,
                            Country = "Thailand",
                            Description = "For major tourist attractions in Bangkok, most of them are Historical sites or religious sites such as temples in Bangkok. There is beautiful architecture, wall painting and also important in History, such as Wat Phra Sri Rattanasamaram (Phra Kaew), Wat Phra Chetuphon Wimon Mangalaram (wat pho), wat arun Ratchawararam, Wat Sra Ket, and Phra Bor Banphot (Golden mountain), Wat Ratchanadda, Wat Traimit, Wat Benchamabophit, Wat Bowonniwet Vihara Suthasan, Wat Thep Wararam etc. ",
                            ImageUrl = "https://www.planetware.com/wpimages/2019/08/thailand-in-pictures-most-beautiful-places-bangkok-riverfront.jpg",
                            Name = "Beauty of Bankok"
                        },
                        new
                        {
                            TravelPlaceID = 15,
                            Country = "South Africa",
                            Description = "Few destinations rival South Africa when it comes to offering a wide range of attractions combined with easy and convenient regional travel. Home to the Big 5 and breath-taking natural beauty, a South Africa safari experience is ideal for families, honeymooners and adventure seekers of all ages. Game reserves are teeming with lion, elephant, buffalo, rhino, rare cheetah, and all the plains game favourites like zebra, giraffe and gazelle. For the ultimate Big 5 safari in South Africa, nothing beats the Kruger National Park – widely considered the best place in Africa to see leopard, the most elusive of all big cats. Accommodation options range from 5-star to star-lit, and include family lodges, honeymoon hideaways, and grand tented camps.",
                            ImageUrl = "https://ssl.tzoo-img.com/images/blog/2019/2/8/ssimg_210.jpg?width=412&spr=3",
                            Name = "Safari South Africa"
                        },
                        new
                        {
                            TravelPlaceID = 16,
                            Country = "Botswana",
                            Description = "Discover the wildlife roaming through one of Africa’s last great wildernesses on a Botswana safari. Desert, marshlands, rivers and the enormous Okavango Delta make this one of the world’s best places for game drives, bush walks and dugout canoe trips, with an array of animals to spot, including the Big Five. Time spent with local guides and bushmen adds to the experience, while low visitor numbers ensure Botswana safaris deliver sensational sights without the crowds.",
                            ImageUrl = "https://www.andbeyond.com/wp-content/uploads/sites/5/Herd-of-Elephants-walking-while-guests-cross-channel-on-a-Safari-Game-Drive-in-Botswana.jpg",
                            Name = "Safari Botswana"
                        },
                        new
                        {
                            TravelPlaceID = 17,
                            Country = "France",
                            Description = "Your chosen destination will depend on your preferences: beaches, towns, access to villages, lively resorts with all facilities, quiet coastal footpaths...most visitors will not expect to explore the entire Cote d'Azur in one trip or have the same requirements from a holiday. Below we guide you to the part of the Cote d'Azur most suitable for your needs, and you can then use the map and the reviews of individual places in the same area to help you decide where to go.If you have no idea where to start exploring, the most visited section of the coast with such famous resorts as Nice, Antibes, Saint-Tropez and Cannes as well as impressive hill villages and areas of great natural beauty is around Nice. Stay on the seafront in Nice and use the train to explore nearby towns and resorts and you will certainly have a good introduction to the Cote d'Azur: see riviera train.",
                            ImageUrl = "https://static.tildacdn.com/tild6333-3963-4232-b139-343838313334/ote-d-azur-cruise-tr.jpeg",
                            Name = "Cote d'Azur"
                        },
                        new
                        {
                            TravelPlaceID = 18,
                            Country = "Spain",
                            Description = "Quite simply, bullfighting is a fight between a bull and a human. This person is known as a bullfighter or a matador. They are attempting to immobilise, subdue or indeed kill the bull – and there are usually rules and regulations for the fighting as well as various cultural expectations. Bullfighting in Spain is, typically, known as Spanish-style bullfighting. This style is practiced outside of the country, in places like Portugal, Mexico, Colombia, Peru, the south of France and more.",
                            ImageUrl = "https://m.psecn.photoshelter.com/img-get/I0000KM3Tgz.EL9c/s/900/600/bullfighting-corrida-spain-40.jpg",
                            Name = "Corida Spain"
                        },
                        new
                        {
                            TravelPlaceID = 19,
                            Country = "China",
                            Description = "‘We’ve broken a Buddha,’ cried the farmers who stumbled across a pottery torso and head as they were digging a well near Xian, northern China. The year was 1974, and little did they know what they’d unearthed: a life-size army of 8,000 warriors and horses built to accompany China’s first emperor, Qin Shi Huang, in the afterlife. To date, only a fraction have been unearthed.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg9Bh1GEsvpvMoAKQZMtxLI8v16ormJMHb8z6usd-oj0PPXq5BLCZkKq2qT_YTavgNfd4&usqp=CAU",
                            Name = "Terakota warriors"
                        },
                        new
                        {
                            TravelPlaceID = 20,
                            Country = "Australia",
                            Description = "The cute and cuddly koala is one of Australia's most well-known (and well-loved) animals. You may know them for their fuzzy ears and large noses, but there's much more to these sleepy marsupials.",
                            ImageUrl = "https://media.istockphoto.com/photos/little-girl-hugs-koala-picture-id626145812?k=20&m=626145812&s=612x612&w=0&h=X11Nn3LhtqlVj_fU0YvnWY_NrcrKF--P34k_nZNHzZA=",
                            Name = "Australia coalas"
                        },
                        new
                        {
                            TravelPlaceID = 21,
                            Country = "Serbia",
                            Description = "While Belgrade’s rich history makes itself reminded throughout the city, most notably in the old Belgrade Fortress, Belgrade features an abundance of cultural attractions and a wide range of events that draw visitors from across Europe.As one of Europe’s oldest cities, located at the crossroads of the East and West, the capital of Serbia is an incredibly rich mosaic of different cultures, influences and styles with a mysterious and exotic atmosphere.European but with oriental influences, Belgrade is a great weekend break, with tons of interesting sights and attractions, splendid architecture, a fast-paced nightlife, great and affordable shopping, as well as a thriving cultural scene.",
                            ImageUrl = "https://images.squarespace-cdn.com/content/v1/59dab4fd8fd4d21d6a6219b3/1508457059277-DQ6HIDC9VDJCVAY7NR4A/belgrade-serbia.jpg?format=2500w",
                            Name = "Belgrade"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Age = 23,
                            FirstName = "Nikola",
                            LastName = "Golubovic",
                            Password = "nikola",
                            Username = "nikola"
                        },
                        new
                        {
                            UserID = 2,
                            Age = 23,
                            FirstName = "Nenad",
                            LastName = "Golubovic",
                            Password = "nenad",
                            Username = "nenad"
                        });
                });

            modelBuilder.Entity("Models.UserArrangementGroup", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("ArrangementGroupID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "ArrangementGroupID");

                    b.HasIndex("ArrangementGroupID");

                    b.ToTable("UserArrangementGroups");
                });

            modelBuilder.Entity("Models.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            UserID = 2,
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("ArrangementArrangementGroup", b =>
                {
                    b.HasOne("Models.ArrangementGroup", null)
                        .WithMany()
                        .HasForeignKey("ArrangementsGroupArrangementGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Arrangement", null)
                        .WithMany()
                        .HasForeignKey("ArrangementsArrangementID", "ArrangementsTravelCompanyID", "ArrangementsTravelPlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Arrangement", b =>
                {
                    b.HasOne("Models.TravelCompany", "TravelCompany")
                        .WithMany("Arrangements")
                        .HasForeignKey("TravelCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TravelPlace", "TravelPlace")
                        .WithMany("Arrangements")
                        .HasForeignKey("TravelPlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelCompany");

                    b.Navigation("TravelPlace");
                });

            modelBuilder.Entity("Models.RolePermission", b =>
                {
                    b.HasOne("Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.UserArrangementGroup", b =>
                {
                    b.HasOne("Models.ArrangementGroup", "ArrangementGroup")
                        .WithMany("UserArrangementGroups")
                        .HasForeignKey("ArrangementGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany("UserArrangements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrangementGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.UserRole", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.ArrangementGroup", b =>
                {
                    b.Navigation("UserArrangementGroups");
                });

            modelBuilder.Entity("Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Models.TravelCompany", b =>
                {
                    b.Navigation("Arrangements");
                });

            modelBuilder.Entity("Models.TravelPlace", b =>
                {
                    b.Navigation("Arrangements");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("UserArrangements");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
